### ISSUE TITLE
Temperature bug (no decimal point?)

### ISSUE THREAD

**Issue by k0rtina** [gabrielpc1190/Home-Assistant_EPEver-eBox-Wifi-01-MODBUS#1]
It appears that the temperature is displayed with 4 digits.

EG: 3113

Where I guess it should read 31.13 deg C.

![image](https://user-images.githubusercontent.com/16025929/97832313-9161ca80-1d26-11eb-901d-755ffd5b1895.png)

**Comment by gabrielpc1190** [comment]
You need to add the `scale: 0.1` plus `precision: 2`
